substitutions:
  rooms_amount: "4"  # Max 4 rooms supported by the template

  room_icon_1: "\U000F04B9"  # mdi:sofa (Living Room)
  room_icon_2: "\U000F04A6"  # mdi:silverware-variant (Kitchen)
  room_icon_3: "\U000F02E3"  # mdi:bed (Bedroom)
  room_icon_4: "\U000F1818"  # mdi:bathtub (Bathroom)

  track_light_icon: "\U000F0914"
  ceiling_light_multiple_icon: "\U000F18DD"
  flor_lamp_icon: "\U000F08DD"
  vanity_light_icon: "\U000F11E1"

packages:
  room_selector: !include room_select.yaml

  living_room: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_1"
      room_icon: "${room_icon_1}"
      lights_amount: "4"
      light_entity_1: "light.living_room_main"
      light_entity_2: "light.tv_backlight"
      light_entity_3: "light.floor_lamp"
      light_entity_4: "light.left_bloom"
      light_icon_1: "${ceiling_light_multiple_icon}"
      light_icon_2: "${track_light_icon}"
      light_icon_3: "${flor_lamp_icon}"
      light_icon_4: "${vanity_light_icon}"

  kitchen: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_2"
      room_icon: "${room_icon_2}"
      lights_amount: "2"
      light_entity_1: "light.kitchen"
      light_entity_2: "light.kitchen_2"
      light_entity_3: "light.kitchen"
      light_entity_4: "light.kitchen_2"
      light_icon_1: "${ceiling_light_multiple_icon}"
      light_icon_2: "${track_light_icon}"
      light_icon_3: "${flor_lamp_icon}"
      light_icon_4: "${vanity_light_icon}"

  bedroom: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_3"
      room_icon: "${room_icon_3}"
      lights_amount: "4"
      light_entity_1: "light.bedroom"
      light_entity_2: "light.bedroom_2"
      light_entity_3: "light.wardrobe"
      light_entity_4: "light.new_lamp"
      light_icon_1: "${ceiling_light_multiple_icon}"
      light_icon_2: "${track_light_icon}"
      light_icon_3: "${flor_lamp_icon}"
      light_icon_4: "${vanity_light_icon}"

  bathroom: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_4"
      room_icon: "${room_icon_4}"
      lights_amount: "2"
      light_entity_1: "light.bathroom"
      light_entity_2: "light.bathroom_2"
      light_entity_3: "light.bathroom"
      light_entity_4: "light.bathroom_2"
      light_icon_1: "${ceiling_light_multiple_icon}"
      light_icon_2: "${track_light_icon}"
      light_icon_3: "${flor_lamp_icon}"
      light_icon_4: "${vanity_light_icon}"
